/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import Spline from '@splinetool/react-spline';

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/jn4J8ZnEUx8XF0Zu/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#000000']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <particleSystem
            name="Particle Emitter"
            geometry={nodes['Particle Emitter'].geometry}
            material={materials['']}
            position={[197.75, 0, -0.73]}
          />
          <mesh
            name="Text"
            geometry={nodes.Text.geometry}
            material={materials['Metal Bi-lightings 02']}
            castShadow
            receiveShadow
            position={[217.3, 300.81, 10.43]}
          />
          <directionalLight
            name="Light Main"
            castShadow
            intensity={1}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[-129.8, 169.47, 157.37]}
          />
          <directionalLight
            name="Key Light"
            castShadow
            intensity={0.2}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[138.73, 169.47, -75.64]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
        </scene>
      </group>
    </>
  )
}
